services:
  # 1. Base de Datos (PostgreSQL)
  kiora-db:
    image: postgres:16-alpine
    container_name: kiora_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
<<<<<<< HEAD
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rootpassword}
=======
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
>>>>>>> origin/main
      POSTGRES_DB: ${DB_NAME:-kiora}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - kiora_db_data:/var/lib/postgresql/data
    healthcheck:
<<<<<<< HEAD
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}" ]
=======
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-kiora}"]
>>>>>>> origin/main
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Interfaz Visual para la BD (pgAdmin)
  kiora-pgadmin:
    image: dpage/pgadmin4
    container_name: kiora_admin_db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kiora.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - kiora_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - kiora-db

  # 3. Redis (blacklist de tokens JWT)
  kiora-redis:
    image: redis:7-alpine
    container_name: kiora_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - kiora_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. Users Service
  users-service:
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    container_name: kiora_users_service
    restart: unless-stopped
    ports:
      - "3002:3001"
    env_file:
      - ./services/users-service/.env
    environment:
      DB_HOST: kiora-db        # Nombre del servicio Docker, no localhost
      DB_PORT: 5432            # Puerto interno del contenedor
      REDIS_HOST: kiora-redis  # Nombre del servicio Redis en Docker
      REDIS_PORT: 6379
    depends_on:
      kiora-db:
        condition: service_healthy
      kiora-redis:
        condition: service_healthy

volumes:
  kiora_db_data:
  kiora_pgadmin_data:
  kiora_redis_data:
